// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpHXxesobfSysmG88FFUBPP6pEjEB6yLU',
    appId: '1:957799988864:web:8453a29815c4ff5984b065',
    messagingSenderId: '957799988864',
    projectId: 'earn-for-all-6d227',
    authDomain: 'earn-for-all-6d227.firebaseapp.com',
    storageBucket: 'earn-for-all-6d227.appspot.com',
    measurementId: 'G-4Y910G9PS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlq5z0pks6zhpRVcGdhaBWPK8xwoaudBQ',
    appId: '1:957799988864:android:cf1e502ce1f71cb084b065',
    messagingSenderId: '957799988864',
    projectId: 'earn-for-all-6d227',
    storageBucket: 'earn-for-all-6d227.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwFlxGYPh9lkj_hvq4DhI72k2b8YV3xdA',
    appId: '1:957799988864:ios:ee184ec1d131a73d84b065',
    messagingSenderId: '957799988864',
    projectId: 'earn-for-all-6d227',
    storageBucket: 'earn-for-all-6d227.appspot.com',
    iosBundleId: 'com.example.earnForAll',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwFlxGYPh9lkj_hvq4DhI72k2b8YV3xdA',
    appId: '1:957799988864:ios:aa10ee12cade524184b065',
    messagingSenderId: '957799988864',
    projectId: 'earn-for-all-6d227',
    storageBucket: 'earn-for-all-6d227.appspot.com',
    iosBundleId: 'com.example.earnForAll.RunnerTests',
  );
}
